### ISSUE TITLE
alot-0.8.tar.gz.asc key expired

### ISSUE THREAD

**Issue by jljusten** [pazz/alot#1356]
When I try to verify the tarball with alot-0.8.tar.gz.asc, it says the key has expired.

@pazz: Did you need to update the expiration on your key? https://superuser.com/a/1141251

**Comment by pazz** [comment]
Thanks for reporting on this jljusten.
I think I updated the expiration date a while back but never published this to keyservers..

```
gpg --list-keys patricktotzke
                                                   
pub   dsa1024 2004-08-21 [SC] [expires: 2020-09-27]
      B7838D65FEE80DED1DCA494D94340367D7D6C5AA
uid           [ultimate] Patrick Totzke <patricktotzke@googlemail.com>
uid           [ultimate] Patrick Totzke (gmail) <patricktotzke@gmail.com>
sub   elg2048 2004-08-21 [E] [expires: 2020-09-27]
```

I've now done a 

```
gpg -v --keyserver pgp.mit.edu --send-keys
echo $?
0
```

The last cmd hopefully confirms that I've pushed my keys!?

Please report back if this solves the issue and if so, close this thread. Thanks!

**Comment by jljusten** [comment]
I'm not sure how long it takes to get updated, but I did just fetch it from pgp.mit.edu on a new system, and it still shows the old date. :\

My ~/.gnupg/gpg.conf has `keyserver hkp://keys.gnupg.net`, but I think the servers synchronize with each other.

**Comment by pazz** [comment]
so my above command was in fact suspiciously fast. I don't know how to debug this. Perhaps I should just push to another server?

**Comment by jljusten** [comment]
I'm not sure, but I don't think it would hurt to upload to multiple servers. I think they exchange with each other, but I'm not sure about that.

You might try leaving the `--keyserver pgp.mit.edu` part off too, since I guess most distros must have some default server that they talk to.

**Comment by pazz** [comment]
It seems that the command i used above expects the keyid as a parameter. I've now hopefully pushed my updated key to the two mentioned servers. Thanks for your help with this!

**Comment by jljusten** [comment]
Yeah, it looks to be updated now. Thanks!
