### ISSUE TITLE
Tree widgets issue with removing last message of  a thread

### ISSUE THREAD

**Issue by pazz** [pazz/alot#700]
When using `remove` on the last message of a thread (i removed a draft msg) I see:

```
Traceback (most recent call last):
  File "/home/pazz/.local/bin/alot", line 20, in <module>
    main()
  File "/home/pazz/.local/lib/python2.7/site-packages/alot/init.py", line 186, in main
    UI(dbman, cmdstring)
  File "/home/pazz/.local/lib/python2.7/site-packages/alot/ui.py", line 87, in __init__
    self.mainloop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 272, in run
    self.screen.run_wrapper(self._run)
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 242, in run_wrapper
    return fn()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 337, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1256, in wrapper
    rval = f(*args,**kargs)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1184, in _twisted_idle_callback
    callback()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 549, in entering_idle
    self.draw_screen()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 563, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1058, in render
    focus and self.focus_part == 'body')
  File "/home/pazz/.local/lib/python2.7/site-packages/alot/buffers.py", line 380, in render
    msg = self.get_selected_message()
  File "/home/pazz/.local/lib/python2.7/site-packages/alot/buffers.py", line 423, in get_selected_message
    return self.get_selected_messagetree()._message
  File "/home/pazz/.local/lib/python2.7/site-packages/alot/buffers.py", line 419, in get_selected_messagetree
    return self._nested_tree[self.body.get_focus()[1][:1]]
AttributeError: 'SolidFill' object has no attribute 'get_focus'
```

**Comment by mturquette** [comment]
I just got the following while refreshing a thread:

```
Traceback (most recent call last):
  File "/usr/bin/alot", line 20, in <module>
    main()
  File "/usr/share/alot/alot/init.py", line 186, in main
    UI(dbman, cmdstring)
  File "/usr/share/alot/alot/ui.py", line 87, in __init__
    self.mainloop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 274, in run
    self.screen.run_wrapper(self._run)
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 268, in run_wrapper
    return fn()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 339, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1183, in wrapper
    rval = f(*args,**kargs)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 1142, in _twisted_idle_callback
    callback()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 551, in entering_idle
    self.draw_screen()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 565, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1079, in render
    focus and self.focus_part == 'body')
  File "/usr/share/alot/alot/buffers.py", line 379, in render
    msg = self.get_selected_message()
  File "/usr/share/alot/alot/buffers.py", line 422, in get_selected_message
    return self.get_selected_messagetree()._message
  File "/usr/share/alot/alot/buffers.py", line 418, in get_selected_messagetree
    return self._nested_tree[self.body.get_focus()[1][:1]]
AttributeError: 'SolidFill' object has no attribute 'get_focus'
```

I do not think that anything was removed. I just refreshed the thread after imap sync to get additional replies and boom.

**Comment by mturquette** [comment]
Is there a graceful way to recover from this stuff? It seems like it blew up alot completely. Why not just bail out of thread view, back to the search view?

**Comment by pazz** [comment]
i pushed a hotfix to `0.3.8-emptythreads-700`. It's not particularly pretty, but let me know how you get on..

**Comment by mturquette** [comment]
I'll test it this week. Alot crashes on me pretty often while browsing huge mail threads on the Linux kernel mailing list. If one blows up alot predictably them I'll try this patch to see if it fixes it.

**Comment by mturquette** [comment]
Finally getting around to testing this. I haven't been able to find a thread that blows up consistently (even though I still get the solidfill error every now and then). I guess I'll use the new branch for a week or two and if I do not receive any problems then we can mark this as solved.

**Comment by mturquette** [comment]
I just hit this bug again using `0.3.8-emptythreads-700`. Same behavior as before:

1. open a thread for viewing in alot
1. go to sleep
1. wake up the next morning
1. fetch imap
 * note that this thread has new messages added to it since yesterday
1. in alot, hit `@`, which is bound to `refresh`
1. explode
