### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'selectable'

### ISSUE THREAD

**Issue by joka** [pazz/alot#839]
I`m running the current develop version of alot with urwid 1.3.1 and  urwidtree  1.0.1.1.
Some mail threads are causing the follwoing exception:

```
% alot                                                                                                                                                                                  
Traceback (most recent call last):
  File "/home/joka/opt/python/bin/alot", line 9, in <module>
    load_entry_point('alot==0.3.7', 'console_scripts', 'alot')()
  File "/home/joka/.local/lib/python2.7/site-packages/alot-0.3.7-py2.7.egg/alot/__main__.py", line 186, in main
    UI(dbman, cmdstring)
  File "/home/joka/.local/lib/python2.7/site-packages/alot-0.3.7-py2.7.egg/alot/ui.py", line 90, in __init__
    self.mainloop.run()
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self.screen.run_wrapper(self._run)
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/raw_display.py", line 272, in run_wrapper
    return fn()
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 343, in _run
    self.event_loop.run()
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 1187, in wrapper
    rval = f(*args,**kargs)
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 1146, in _twisted_idle_callback
    callback()
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 555, in entering_idle
    self.draw_screen()
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/main_loop.py", line 569, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/container.py", line 1079, in render
    focus and self.focus_part == 'body')
  File "/home/joka/.local/lib/python2.7/site-packages/alot-0.3.7-py2.7.egg/alot/buffers.py", line 410, in render
    return self.body.render(size, focus)
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/widget.py", line 1751, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/listbox.py", line 457, in render
    (maxcol, maxrow), focus=focus)
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/listbox.py", line 402, in calculate_visible
    next, pos = self.body.get_next( pos )
  File "/home/joka/.local/lib/python2.7/site-packages/urwidtrees/widgets.py", line 82, in get_next
    return self._get(self._tree.next_position(pos))
  File "/home/joka/.local/lib/python2.7/site-packages/urwidtrees/widgets.py", line 68, in _get
    res = self[pos], pos
  File "/home/joka/.local/lib/python2.7/site-packages/urwidtrees/lru_cache.py", line 102, in wrapper
    result = user_function(*args, **kwds)
  File "/home/joka/.local/lib/python2.7/site-packages/urwidtrees/widgets.py", line 54, in __getitem__
    entry = self._tree.get_decorated(pos)
  File "/home/joka/.local/lib/python2.7/site-packages/urwidtrees/nested.py", line 86, in get_decorated
    return self._get_decorated_entry(self._tree, pos)
  File "/home/joka/.local/lib/python2.7/site-packages/urwidtrees/nested.py", line 82, in _get_decorated_entry
    entry = tree.decorate(pos[0], entry, is_first=isf)
  File "/home/joka/.local/lib/python2.7/site-packages/urwidtrees/decoration.py", line 475, in decorate
    line = urwid.Columns(cols, box_columns=range(len(cols))[:-1])
  File "/home/joka/.local/lib/python2.7/site-packages/urwid/container.py", line 1761, in __init__
    if focus_column is None and w.selectable():
AttributeError: 'NoneType' object has no attribute 'selectable'


``` 

This only happens since i had to reinstall alot, unfortunately  i don't know the old working version
of alot. I tried using older versions of alot/urwid/urwidtree without success.
Can you give me a hint how to debug this?

**Comment by pazz** [comment]
Quoting Joscha Krutzki (2016-02-06 16:59:48)
>    File "/home/joka/.local/lib/python2.7/site-packages/urwidtrees/decoration.py", line 475, in decorate
>      line = urwid.Columns(cols, box_columns=range(len(cols))[:-1])
>    File "/home/joka/.local/lib/python2.7/site-packages/urwid/container.py", line 1761, in __init__
>      if focus_column is None and w.selectable():
>  AttributeError: 'NoneType' object has no attribute 'selectable'

Thanks for this detailed bug report :)

It looks like `cols`, which should be a list of urwid widgets, contains None for
some reason. I think the best way to debug this would be to add some debug
statements printing the content of this variable and then going backwards,
checking what introduced this None value.
I suspect it is some unexpected header value or tag string that introduces this.

**Comment by joka** [comment]
ok, the problem was  i have empty mail files in my maildir directory.

I close this issue as invalid.

**Comment by josch** [comment]
Hi, I didn't see this bug report when I filed #842 because it was closed at the time. In #842 I show an email which triggers this behaviour for me. But even an empty mail file as described in this bug report should not have this effect.

**Comment by pazz** [comment]
no worries.
I agree it is a bug. there  should be some test for something being not None
somewhere..

Quoting josch (2016-02-19 12:33:30)

**Comment by pazz** [comment]
I believe this is an issue with urwidtrees.
I pushed a patch that should fix this issue, see  https://github.com/pazz/urwidtrees/commit/1da928f90bb5848a22932840393fbb9853bd9fd6.
Please update urwidtrees and let me know how it goes.

**Comment by josch** [comment]
I cannot confirm that this fixes it for me. The problem still persists with the email I posted in #842.
